  language: python

  python:
    - "3.6"
    - "3.5"

  install:
    - pip install -r requirements.txt
    - pip install codecov

  services:
    - redis

  env:
    - FLASK=0.10.1
    - FLASK=0.12.2

  before_script:
    - psql -c 'create database my_test_database;' postgres
    - psql -c 'create database my_database;' postgres

  script:
    - python -m pytest
    - coverage run test_case.py

  after_success:
    - codecov
