  language: python

  python:
    - "3.6"
    - "2.7"

  install:
    - pip install -r requirements.txt

  services:
    - redis

  env:
    - FLASK=0.10.1
    - FLASK=0.12.2

  before_script:
    - psql -c 'create database my_test_database;' postgres

  script:
    - python -m pytest
